#!/usr/bin/env bash

### A convenience script to run Docker Compose commands.

set -o errexit
set -o nounset
set -o noclobber
set -o pipefail

environment="${1}"
shift
params="${*}"

export ENVIRONMENT="${environment}"

GIT_COMMIT_SHA="$(git rev-parse HEAD)"
export GIT_COMMIT_SHA

# Make sure Docker Volumes are always mounted under the current user and group IDs to avoid
# file system permission issues:
DOCKER_UID="$(id -u)"
export DOCKER_UID
DOCKER_GID="$(id -g)"
export DOCKER_GID

docker_options="${DOCKER_OPTIONS:-}"

docker_compose_options='--file ./docker-compose.yml'
case "${ENVIRONMENT}" in
'development')
  docker_compose_options="${docker_compose_options} --file ./docker-compose.override.yml"
  ;;

'production')
  set -o allexport
  . remote_host.env
  set +o allexport
  docker_compose_options="${docker_compose_options} --file ./docker/docker-compose.prod.yml"
  ;;

*)
  echo "The '${ENVIRONMENT}' environment is not supported."
  exit 1
  ;;
esac
# shellcheck disable=SC2236
if [[ ! -z "${DOCKER_COMPOSE_OPTIONS+x}" ]]; then
  docker_compose_options="${docker_compose_options} ${DOCKER_COMPOSE_OPTIONS}"
fi

docker ${docker_options} compose ${docker_compose_options} ${params}
