---

# This compose-file is production only. So, it should not be called directly.
#
# Instead, it should be a part of your deployment strategy.
# This setup is supposed to be used with `docker-swarm`.
# See `./docs/pages/template/production.rst` docs.

version: "3.8"
services:
  caddy:
    image: "caddy:2.7.4"
    restart: unless-stopped
    env_file: ./config/.env
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile  # configuration
      - ./docker/caddy/ci.sh:/etc/ci.sh  # test script
      - caddy-config:/config  # configuration autosaves
      - caddy-data:/data  # saving certificates
      - web-static:/var/www/web/static  # serving web's statics
      - web-media:/var/www/web/media  # serving web's media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - proxynet

  web:
    <<: &web
      # Image for production:
      image: "registry.gitlab.com/{{ cookiecutter.organization }}/{{ cookiecutter.project_name }}:latest"
      build:
        target: production_build

      restart: unless-stopped
      volumes:
        - web-media:/var/www/web/media  # since in dev it is app's folder
        - web-locale:/code/locale  # since in dev it is app's folder

    command: bash ./docker/web/gunicorn.sh
    networks:
      - proxynet
    expose:
      - 8000

# This task is an example of how to extend existing ones:
#   some_worker:
#     <<: *web
#     command: python manage.py worker_process
#     deploy:
#       replicas: 2

networks:
  # Network for your proxy server and application to connect them,
  # do not use it for anything else!
  proxynet:

volumes:
  web-media:
  web-locale:
  caddy-config:
  caddy-data:
